# Form implementation generated from reading ui file 'StudentFrame.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StudentFrame(object):
    def setupUi(self, StudentFrame):
        StudentFrame.setObjectName("StudentFrame")
        StudentFrame.resize(492, 225)
        self.verticalLayout = QtWidgets.QVBoxLayout(StudentFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lay_line1 = QtWidgets.QHBoxLayout()
        self.lay_line1.setObjectName("lay_line1")
        self.lay_login = QtWidgets.QVBoxLayout()
        self.lay_login.setSpacing(0)
        self.lay_login.setObjectName("lay_login")
        self.login_lbl = QtWidgets.QLabel(parent=StudentFrame)
        self.login_lbl.setObjectName("login_lbl")
        self.lay_login.addWidget(self.login_lbl)
        self.login_edt = QtWidgets.QLineEdit(parent=StudentFrame)
        self.login_edt.setObjectName("login_edt")
        self.lay_login.addWidget(self.login_edt)
        self.lay_line1.addLayout(self.lay_login)
        self.lay_fio = QtWidgets.QVBoxLayout()
        self.lay_fio.setSpacing(0)
        self.lay_fio.setObjectName("lay_fio")
        self.fio_lbl = QtWidgets.QLabel(parent=StudentFrame)
        self.fio_lbl.setObjectName("fio_lbl")
        self.lay_fio.addWidget(self.fio_lbl)
        self.fio_edt = QtWidgets.QLineEdit(parent=StudentFrame)
        self.fio_edt.setObjectName("fio_edt")
        self.lay_fio.addWidget(self.fio_edt)
        self.lay_line1.addLayout(self.lay_fio)
        self.lay_line1.setStretch(0, 1)
        self.lay_line1.setStretch(1, 2)
        self.verticalLayout.addLayout(self.lay_line1)
        self.lay_email = QtWidgets.QVBoxLayout()
        self.lay_email.setSpacing(0)
        self.lay_email.setObjectName("lay_email")
        self.email_lbl = QtWidgets.QLabel(parent=StudentFrame)
        self.email_lbl.setObjectName("email_lbl")
        self.lay_email.addWidget(self.email_lbl)
        self.email_edt = QtWidgets.QLineEdit(parent=StudentFrame)
        self.email_edt.setObjectName("email_edt")
        self.lay_email.addWidget(self.email_edt)
        self.verticalLayout.addLayout(self.lay_email)
        self.lay_comment = QtWidgets.QVBoxLayout()
        self.lay_comment.setSpacing(0)
        self.lay_comment.setObjectName("lay_comment")
        self.comment_lbl = QtWidgets.QLabel(parent=StudentFrame)
        self.comment_lbl.setObjectName("comment_lbl")
        self.lay_comment.addWidget(self.comment_lbl)
        self.comment_edt = QtWidgets.QTextEdit(parent=StudentFrame)
        self.comment_edt.setObjectName("comment_edt")
        self.lay_comment.addWidget(self.comment_edt)
        self.verticalLayout.addLayout(self.lay_comment)

        self.retranslateUi(StudentFrame)
        QtCore.QMetaObject.connectSlotsByName(StudentFrame)

    def retranslateUi(self, StudentFrame):
        _translate = QtCore.QCoreApplication.translate
        StudentFrame.setWindowTitle(_translate("StudentFrame", "Frame"))
        self.login_lbl.setText(_translate("StudentFrame", "Login"))
        self.fio_lbl.setText(_translate("StudentFrame", "Fullname N. P."))
        self.email_lbl.setText(_translate("StudentFrame", "e-mail"))
        self.comment_lbl.setText(_translate("StudentFrame", "Comment"))
